export const CLIENT_SECRET = 'CZZ3W25U4LSDXVJIBF3AQNQN0H1FJDYXQX1Z3MDZDF0RK4RX'
export const CLIENT_ID = 'Z1NDJTIIKGU2JW4PCYKKITBCUHPQBTGOREJNYADRLMPXYJI3'
export const BASE_API_URL = 'https://api.foursquare.com/v2/'
export const GET_LUNCH_PLACES = 'GET_LUNCH_PLACES'
export const CLEAR_LUNCH_PLACES = 'CLEAR_LUNCH_PLACES'
export const GET_ERROR_RESPONSE = 'GET_ERROR_RESPONSE'
export const CLEAR_ERROR_RESPONSE = 'CLEAR_ERROR_RESPONSE'
export const SUCCESS_RESPONSE = 200

export const apiConstants = {
  GET_REQUEST: 'get',
  API_REQUEST_START: 'API_REQUEST_START',
  API_REQUEST_FINISH: 'API_REQUEST_FINISH'
}